dist: bionic
language: python
python:
- '3.6'
- '3.7'
sudo: false
install: pip install .
script: py.test
deploy:
  provider: packagecloud
  repository: python
  username: freenome
  dist: python
  token:
    secure: LAUSlZC/w3bFjG1VcLQQWHvlLfKuDbCxTzACYdH7SdBraGKHsrO1yAtE6QHq7eEwQPhKrg1ao04syFzl8sGU9kDt2P41SO/31UHEF9jJ8QHfXp17fOgKoaRBxQnZpznzUncNFfodDBUovNk0vfhCj2yc0N1300UPuAnm4DNl9PagCYpUT6eL8Oi6d+aCMWIeB6fg7nzpvnDHVKc0WyOTRsxptWUXy4AvhSzPzptAJPQR0z9qcY63NLH7WAMIWAUP+ay3ztyFOHGoNMc5RwpiuL1zCIun7dM+kqPvdaXVCqk5m5lxIWKR058d7JDcE0rBxJIFODWlQ1fVK+MioS6dxjTx4Nu408B5d+mWiPqCNQYT6hbskexG+Z18dg96IrrmKcVzjDcjxaJ+5apfRE+PFCwqKagaifzw+GR7EpwTGa2hOrvOJ2/dlMe1LjDYruwB1y1nQzQjPDIOY/TyPQS8ivvp1Aw+woaufLDWRHbGQm3j4uea6/63bKsL7z83MB5JbaPFIR0NL68BPI+oTIDyRrs3vz07NkdA+YkrQ1gUxG66mBIIjYhVYbFaPaRYN7dcdcir+fsANmruFatKn+swZBVwcTYGCFUZJh/ox8jz73t39hBIctoBD4oBijgzlLSLZqJPwvV1ktreLT7toxDu2QG8/yA+6ZO3zvjOaHn2HJ4=
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH =~ ^release/"
