dist: bionic
language: python
python:
- '3.6'
- '3.7'
sudo: false
install: pip install .
script: py.test
deploy:
  provider: packagecloud
  repository: python
  username: freenome
  dist: python
  token:
    secure: g7l34A8lC69tz531WgFyyEb2OmjaYIhYXLAsQB9yn0jy6ybvTAmVNymube8OFNtw40gova29wVuWK/6y7hWmdqAheQI8QqGNDabR0a0pyozjqiP3kjolaKhmB/xyFsUmcP0alAN0yQ5Pwmx3H6oVJm5H6MyXJnV10iNGop28zC0NH1QmyUyewr4TpgMEXJoMr86o16x6IyGgjy4Ujbdb56cdNmvPd8BMJaL8J8W4ua0Kn2gyVCXx+TPR6gj2BfJ1oMa3IQpG9emnDYhdFSL5Q5f4kkvHU7GNHinoa9pszSZYLR52MXElqDHx4jrRi/LHiCrfHUep/Q8G16kKId+e70VdvjEhg6f947HqOAqIhf9ILAW6U3qeqOowetmOMGxZkAqlTq7Os8QbScMVXlWiVlCi2gLuDJYYopMof0+1CyeWqBcsrE7fkmlKjiCiQrY454i+QPmVhjgapFvKv+9TVvSNYgcfY0PyED+qXtEpKi1DfrqH7bqCjnsljIuQFwm8pfjYKJIHngljfFQBvI0SvChLiemNTeCryC9aA45IF/cJLz8fdB6EiT+XDKzhM3ohjoMZPwU+08Q9MFADgGhAWJBiueO8yrdRGr1PwUhMtYe1QOGSMn0F6Ed6+jx+zw6X+WWPQwG8y78t1O6dz6k+U4Nk4VQHNcl9i3xuTKANvLE=
  on:
    all_branches: true
    condition: "$TRAVIS_BRANCH =~ ^release/"
